[project]
name = "wave-guide"
version = "0.1.0"
description = "Your personal music journey."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.uv.workspace]
members = [
    "modules/*",
]
