[project]
name = "module2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["requests>=2.31.0", "module1"]

[tool.uv.sources]
module1 = { workspace = true }
